name: Build Simple Live

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-android
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-windows
          path: build/windows/runner/Release/
          retention-days: 30

  # iOS构建需要证书，这里只提供基础配置
  build-ios:
    name: Build iOS (Requires Code Signing)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install

      - name: Build iOS (debug, no signing)
        run: flutter build ios --debug
        continue-on-error: true # iOS构建可能因签名失败，但允许继续

      - name: Upload iOS artifact if built
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-ios-debug
          path: build/ios/
          retention-days: 30
        if: success() || failure() # 即使构建部分失败也上传
